languageCode = "en-us"
title = "jarv.org"
theme = "one-post-a-year"
baseURL = 'https://jarv.org/'
pygmentsCodeFences = true

[params]
  description = "random thoughts and posts on tech"
  smDemo = "http://localhost:8760/view/DEMO"
  smEmbed = "http://localhost:8760/embed/DEMO?question=false"
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    noClasses = false
    # https://xyproto.github.io/splash/docs/longer/all.html
    # Classes included in this theme for the following two styles:
      # style = 'github'
      # style = 'solarized-dark'
    tabWidth = 2
    lineNos = false
    lineNumbersInTable = false
[markup.goldmark.renderer]
  unsafe = "true"
