languageCode = "en-us"
title = "jarv.org"
theme = "one-post-a-year"
baseURL = 'https://jarv.org/'
pygmentsCodeFences = true

[params]
  description = "random thoughts and posts on tech"
  wshost = "127.0.0.1:8710"

[markup.goldmark.renderer]
  unsafe = "true"
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    noClasses = false
    # https://xyproto.github.io/splash/docs/longer/all.html
    # Classes included in this theme for the following two styles:
      # style = 'github'
      # style = 'solarized-dark'
    tabWidth = 2
