stages:
  - build
  - deploy

before_script:
  - pip install -r requirements.txt

build:
  image: registry.gitlab.com/jarv/jarv.org/ci-image
  stage: build
  script:
    - make clean
    - make html

deploy_draft:
  image: registry.gitlab.com/jarv/jarv.org/ci-image
  stage: deploy
  script:
    - make clean
    - export S3_BUCKET=draft.jarv.org
    - make s3_upload

deploy_prod:
  image: registry.gitlab.com/jarv/jarv.org/ci-image
  stage: deploy
  script:
    - make clean
    - export S3_BUCKET=jarv.org
    - make s3_upload
  only:
    - master
