stages:
  - build
  - deploy

.deploy:
  image: registry.gitlab.com/jarv/jarv.org/ci-image
  stage: deploy
  script:
    - make clean
    - export S3_BUCKET=$S3_BUCKET
    - export DISTID=$DISTID
    - make s3_upload

before_script:
  - git submodule update --init --recursive
  - pip install -r requirements.txt

build:
  image: registry.gitlab.com/jarv/jarv.org/ci-image
  stage: build
  script:
    - make clean
    - make html

deploy:draft:
  extends: .deploy
  resource_group: deploy:draft
  variables:
    S3_BUCKET: draft.jarv.org
    DISTID: E1B0Q0MMPJQ79F
  environment:
    name: draft
    url: https://draft.jarv.org

deploy:prod:
  extends: .deploy
  resource_group: deploy:prod
  variables:
    S3_BUCKET: jarv.org
    DISTID: EEN9NFVIDRTGS
  environment:
    name: jarv
    url: https://jarv.org
  when: manual
