stages:
  - build
  - deploy

before_script:
  - docker info
  - pip install -r requirements.txt

test:
  image: registry.gitlab.com/jarv/jarv.org/ci-image
  stage: build
  script:
    - make clean
    - make html

deploy:
  image: registry.gitlab.com/jarv/jarv.org/ci-image
  stage: deploy
  script:
    - echo deploy
  only:
    - master
