[tasks.serve]
run = "hugo server -D -F"

[tasks.rebuild]
run = """
#!/usr/bin/env bash

set -e

ssh root@i.jarv.org '/usr/local/bin/rebuild-jarv-org'
"""

[tools]
golang = "1.24"
hugo = "0.124.1"
vale = "3.3.0"
nodejs = "22.14.0"
shellcheck = "0.9.0"
watchexec = "latest"
