languageCode = "en-us"
title = "jarv.org"
theme = "kiera"
pygmentsCodeFences = true
copyright = "Copyright 2007-{year}"
description = "Hugo Theme for creative and technical writing"

[author]
  name = "jarv"
  gitlab = "jarv"
  email = "john@jarv.org"

[markup.goldmark.renderer]
  unsafe = "true"
